main/src/JAG.DevTest2019.WebHost/Models/Lead.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAG.DevTest2019.Host.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lead()
        {
            this.LeadParameter = new HashSet<LeadParameter>();
        }
    
        public string Leadid { get; set; }
        public Nullable<int> TrackingCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> ReceivedDateTime { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
        public string ReferrerURL { get; set; }
        public Nullable<bool> IsDuplicate { get; set; }
        public Nullable<bool> IsCapped { get; set; }
        public Nullable<bool> IsSuccessful { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadParameter> LeadParameter { get; set; }
    }
}

main/src/JAG.DevTest2019.WebHost/Models/LeadViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JAG.DevTest2019.Host.Models
{
    public class LeadViewModel
    {
        public LeadViewModel()
        {
            Results = new LeadResultViewModel();
        }

        public string TrackingCode { get; }

        
        [Display(Name = "Select your gender?")]
        public string Gender { get; set; }

        [Display(Name = "Select your language?")]
        public string Language { get; set; }

        [Display(Name = "Select your blood type?")]
        public string BloodType { get; set; }

        [Required (ErrorMessage = "'First Name is Required'")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required (ErrorMessage = "'Surname is Required'")]
        [Display(Name = "Surname")]
        public string Surname { get; set; }


        //[RegularExpression(@"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z",ErrorMessage = "Please enter correct email address")]
        [Required(ErrorMessage = "'Email address is Required'")]
        [Display(Name = "Email Address")]
        public string EmailAddress { get; set; }

        [Required]
        [MaxLength(13)]
        [MinLength(10)]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Contact Number must be numeric")]
        [Display(Name = "Contact Number")]
        public virtual string ContactNumber { get; set; }

        public List<SelectListItem> Genders { get; } = new List<SelectListItem>()
        {
            new SelectListItem()  {Text="Male", Value = "Male"},
            new SelectListItem()  {Text="Female", Value = "Female"},
        };

        public List<SelectListItem> Languages { get; } = new List<SelectListItem>()
        {
            new SelectListItem()  {Text="English", Value = "English"},
            new SelectListItem()  {Text="Afrikaans", Value = "Afrikaans"},
            new SelectListItem()  {Text="Zulu", Value = "Zulu"},
            new SelectListItem()  {Text="Xhosa", Value = "Xhosa"},
            new SelectListItem()  {Text="Sesotho ", Value = "Sesotho"},
        };

        public List<SelectListItem> BloodTypes { get; } = new List<SelectListItem>()
        {
            new SelectListItem()  {Text="O+", Value = "O+"},
            new SelectListItem()  {Text="O-", Value = "O-"},
            new SelectListItem()  {Text="A+", Value = "A+"},
            new SelectListItem()  {Text="A-", Value = "A-"},
            new SelectListItem()  {Text="B+", Value = "B+"},
            new SelectListItem()  {Text="B-", Value = "B-"},
            new SelectListItem()  {Text="AB+", Value = "AB+"},
            new SelectListItem()  {Text="AB-", Value = "AB-"},
        };

        public LeadResultViewModel Results { get; set; }
    }
}

main/src/JAG.DevTest2019.WebHost/Controllers/LeadController.cs
using JAG.DevTest2019.Host.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace JAG.DevTest2019.Host.Controllers
{
    public class LeadController : Controller
    {
        public ActionResult Index()
        {
            return View(new LeadViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitLead(LeadViewModel model)
        {
            //TODO: 6. Call the WebAPI service here & pass results to UI

            

            LeadViewModel result = new LeadViewModel()
            {
                Results = new LeadResultViewModel()
                {
                   LeadId = new Random().Next(),
                    IsSuccessful = true,
                    Message = "Thank you for submitting your details"
                }
            };

            

            return View("Index",result);
        }

        }
}

main/src/JAG.DevTest2019.WebHost/Views/Lead/Index.cshtml
@{
    Layout = "~/Views/shared/_LeadLayout.cshtml";
    ViewBag.Title = "Page title";
}
@using JAG.DevTest2019.Host.Models
@model LeadViewModel

@section Meta{
    <meta name="description" content="Default site" />
    <meta name="keywords" content="Default" />
}

<section id="quote" class="main-banner row" style="background-image: url(/Content/Images/Banners/car-insurance.jpg)">
    <div class="slant-left col-md-9 pull-left">
        <div class="col-md-8 col-md-offset-2">
            <div class="capture-form">
                <h1 class="text-center">Insurance</h1>
                <h4>Don’t pay too much, find the best insurance quotes and start saving today!</h4>

                @*using (Html.BeginForm("SubmitLead", "Lead", FormMethod.Post, new { id = "frmsubmit" }))*@

                @using (Ajax.BeginForm("SubmitLead", "Lead", null, new AjaxOptions
                {
                    HttpMethod = "POST",
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "FormOuter"
                }))
                {
                    @Html.AntiForgeryToken();
                    <div class="col-md-12">
                        <p>
                            <input type="hidden" value="@Model.TrackingCode" id="hdnTrackingCode" />

                            My name is
                            @Html.TextBoxFor(model => model.FirstName, new { @placeholder = Html.DisplayNameFor(model => model.FirstName) })
                            @Html.ValidationMessageFor(model => model.FirstName)

                            @Html.TextBoxFor(model => model.Surname, new { @placeholder = Html.DisplayNameFor(model => model.Surname) })
                            @Html.ValidationMessageFor(model => model.Surname)
                            You can contact me at
                            @Html.TextBoxFor(model => model.EmailAddress, new { @placeholder = Html.DisplayNameFor(model => model.EmailAddress) })
                            @Html.ValidationMessageFor(model => model.EmailAddress) or
                            @Html.TextBoxFor(model => model.ContactNumber, new { @placeholder = Html.DisplayNameFor(model => model.ContactNumber) })
                            @Html.ValidationMessageFor(model => model.ContactNumber)
                            to help me save on insurance
                            I am
                            @Html.DropDownListFor(model => model.Gender, Model.Genders, "Gender") and my language preference is
                            @Html.DropDownListFor(model => model.Language, Model.Languages, "Language")
                            and my blood type is @Html.DropDownListFor(model => model.Language, Model.BloodTypes, "BloodType")
                        </p>
                    </div>
                    <div class="clearfix"></div>


                    <div class="col-md-12 text-center">
                        <button type="submit" id="btnSubmit" class="orange-button">Get Quotes Now</button>
                    </div>
                }
                @if (Model.Results != null &&
                    Model.Results.IsSuccessful)
                {
                    <div class="col-md-12 text-center">
                        <img src="~/Content/Images/Products/new-success.png" height="24px" />
                        @Html.ValueFor(model => model.Results.Message)
                    </div>
                }
                else
                {
                    <div class="col-md-12 text-center">
                        <img src="~/Content/Images/Products/new-success.png" height="24px" />
                        @Html.ValueFor(model => model.Results.Message)
                    </div>
                }


                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</section>
<div class="clearfix"></div>
<div class="container benefits-padding text-center">
    <h2>Benefits</h2>
    <div class="benefits-cols row">
        <div class="col-md-3 text-center text-instructions">
            <img src="~/Content/Images/Products/new-save.png" />
            <p>People saved on insurance</p>
        </div>
        <div class="col-md-3 text-center text-instructions">
            <img src="~/Content/Images/Products/new-calling.png" />
            <p>99.99% were called in under 5 minutes</p>
        </div>
        <div class="col-md-3 text-center text-instructions">
            <img src="~/Content/Images/Products/new-success.png" />
            <p>96% believe these stats</p>
        </div>
        <div class="col-md-3 text-center text-instructions">
            <img src="~/Content/Images/Products/new-clients.png" />
            <p>Over <span id="served_value"> </span> queries serviced</p>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<div id="quote" class="testimonial-banner" style="background-image: url('../../Content/Images/Banners/best-car-insurance.jpg');">
    <div class="slant-right col-md-9 pull-right">
        <div class="col-md-6 col-md-offset-3 testimonials text-center">
            <b>Getting the lowest insurance quote has never been so easy:</b>
            <p>
                <b>Joe Blogs (26 years)</b><br /><br />
                Telsa model x <br />
                Was paying R999,999.99<br />
                Now paying R99.99
            </p>
            <h2 class="highlight">Insurance saving of {lots of %}</h2>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>
<div class="container-blue">
    <div class="col-md-6 col-md-offset-3 text-center">
        <h1>Get a quote and</h1>
        <h1 class="green">start saving now</h1>
        <p>Get in touch to receive insurance quotes from South Africa’s top insurance companies. Getting the lowest insurance premiums has never been so easy.</p>
        <a id="lnkGetQuote" href="#quote" class="orange-button">Get a quote now</a>
    </div>
    <div class="clearfix"></div>
</div>



@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#lnkLead').addClass('activeMenu');

            var servedValue = 6000000;
            $('#served_value').text(servedValue);

            setInterval(function () {
                var randomValue = Math.floor((Math.random() * 20) + 1);
                servedValue += randomValue;
                $('#served_value').text(servedValue);
            }, 3000);

        });
    </script>

    <script>

        var $form = $("#myform");
        var $submitbutton = $("#submitbutton");

        $form.on("blur", "input", () => {
            if ($form.valid()) {
                $submitbutton.removeAttr("disabled");
            } else {
                $submitbutton.attr("disabled", "disabled");
            }
        });


    </script>

    <Script type="text/javascript">
        $(document).click("orange-button")
    </Script>


    <script type="text/javascript">
        // call ASP.NET MVC Controller 
        function SerializeMappings() {
            var matches = [];

            $('[class^="mappings_"]:checked').each(function () {
                matches.push(this.value);
            });

            $.post("/Home/Validate", { listofmappings: matches }, function (data) {
                document.write(data);
            });
        }
    </script>
}